env: "local"

# HTTP Server Configuration
http_server:
  address: "0.0.0.0:8000"
  timeout: "10s"
  idle_timeout: "60s"
  user: "${HTTP_USER:-abdu1bari}"
  password: "${HTTP_PASSWORD}"

# Database Configuration (PostgreSQL)
database:
  host: "${DB_HOST:-127.0.0.1}" # host: "${DB_HOST}"

  port: "${DB_PORT:-5432}" # port: "${DB_PORT}"

  user: "${DB_USER:-postgres}"
  password: "${DB_PASSWORD:-postgres}"
  dbname: "${DB_NAME:-postgres}"
  sslmode: "disable"

rabbitmq:
  brokers: ["localhost:9092"]
  topic: "transfer-requests"
  group_id: "transfer-group"

log:
  level: "debug"
  format: "json"

# Migration settings (reuses database credentials)
migrations:
  dir: "./migrations"
  table: "schema_migrations"

  # goose -dir ./migrations postgres "user=postgres password=postgres dbname=postgres host=127.0.0.1 port=5432 sslmode=disable" down
  # export PATH=$PATH:$(go env GOPATH)/bin


  # goose -dir ./internal/storage/postgres/migrations postgres "user=postgres password=postgres dbname=postgres host=127.0.0.1 port=5432 sslmode=disable" down